// frontend/src/components/SearchInput.jsx
import React from 'react'
import '../styles/SearchInput.css'

const SearchInput = () => {
  return (
    <div className='search-input-container'>
      <span className="material-symbols-outlined search-input-icon">search</span>
      <input type="text" name="search" placeholder="Find your tutorial" className='search-input' onFocus={(e) => console.log(document.getElementsByClassName('search-input-icon').style.color)}/>
    </div>
  )
}

export default SearchInput

// frontend_angular/src/app/search-input/search-input.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-search-input',
  standalone: true,
  imports: [],
  template: `
    <section class='search'>
      <span class="material-symbols-outlined search-input-icon">search</span>
      <input type="text" name="search" placeholder="Find your tutorial" class='search-input' />
    </section>
  `,
  styleUrl: './search-input.component.css'
})
export class SearchInputComponent {

}
