// frontend/src/pages/Home.jsx
import React from 'react'
import '../styles/Home.css'
import Homepage_Background from '../assets/Homepage_Background.mp4'
import SearchInput from '../components/SearchInput'

const Home = () => {
  return (
    <div className='home-page-container'>
        <video autoPlay muted loop className='home-page-background-video'>
            <source src={Homepage_Background} type='video/mp4'/>
        </video>
        <div className="home-page-header-section">
          <h1 className="home-page-header">All tutorials in one place</h1>
          <span className="home-page-description">Discover tutorials created by our community</span>
          <SearchInput />
        </div>
    </div>
  )
}

export default Home

// frontend_angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { SearchInputComponent } from '../../components/search-input/search-input.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [SearchInputComponent],
  template: `
    <article class='home'>
        <video autoPlay muted loop class='home-background-video'>
            <source src='/Homepage_Background.mp4' type='video/mp4'/>
        </video>
        <section class="home-hero-section">
          <h1 class="home-hero-header">All tutorials in one place</h1>
          <span class="home-hero-description">Discover tutorials created by our community</span>
          <app-search-input/>
        </section>
    </article>
  `,
  styleUrl: './home.component.css'
})
export class HomeComponent {

}
